image: node:current

variables:
  NODE_ENV: production
  # CI_DEBUG_TRACE: "false"

default:
  before_script:
    - yarn install --ignore-scripts # ignoro il post install che chiama nuxt e da errore not found

cache:
  paths:
    - node_modules

stages:
  - test

unit-tests:
  stage: test
  script:
    - echo "Running unit tests..."
