image: node:12

variables:
  NODE_ENV: production
  CI_DEBUG_TRACE: "true"

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm run generate
  artifacts:
    paths:
    - public
  except:
    - master
