image: node:lts

variables:
  NODE_ENV: production
  # CI_DEBUG_TRACE: "false"

default:
  before_script:
    - corepack enable # install Yarn 4
    - yarn set version stable
    - yarn

cache:
  paths:
    - node_modules

stages:
  - test

unit-tests:
  stage: test
  script:
    - echo "Running unit tests..."
