onlyBuiltDependencies:
  - '@parcel/watcher@2.5.6'
  - esbuild@0.18.20
  - esbuild@0.25.12
  - esbuild@0.27.4
  - sharp@0.32.6
  - sharp@0.34.5
  - unrs-resolver@1.11.1
  - vue-demi@0.14.10(vue@3.5.30(typescript@5.9.3))
